name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code
      - name: Récupération du code
        uses: actions/checkout@v4

      # 2️⃣ Login Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Rendre mvnw exécutable
      - name: Rendre mvnw exécutable
        run: chmod +x ./springboot/app/mvnw

      # 4️⃣ Compiler le backend Spring Boot
      - name: Build Spring Boot jar
        run: |
          cd springboot/app
          ./mvnw clean package -DskipTests

      # 5️⃣ Build Docker image Backend
      - name: Build Backend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-backend:latest ./springboot/app

      # 6️⃣ Build Docker image Frontend
      - name: Build Frontend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/angular-frontend:latest ./angular-app

      # 7️⃣ Push Backend
      - name: Push Backend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-backend:latest

      # 8️⃣ Push Frontend
      - name: Push Frontend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/angular-frontend:latest

      # 9️⃣ Lancer application pour test
      - name: Lancer application (test CI)
        run: docker compose up -d

      # 🔟 Vérifier conteneurs
      - name: Vérifier conteneurs
        run: docker ps