name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-backend:latsest ./springboot/app

      - name: Build Frontend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/angular-frontend:latest ./angular-app

      - name: Push Backend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-backend:latest

      - name: Push Frontend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/angular-frontend:latest

      - name: Lancer application (test CI)
        run: docker compose up -d

      - name: Vérifier conteneurs
        run: docker ps